### ISSUE TITLE
AWS AppConfig Improvements (Validation)

### ISSUE THREAD

**Issue by jshlbrd** [brexhq/substation#58]
**Is your feature request related to a problem? Please describe.**

From [the 2023 roadmap](https://github.com/brexhq/substation/discussions/45), data pipelines use AWS AppConfig by default and we can improve our integration with the service by adding support for [config validation](https://docs.aws.amazon.com/appconfig/2019-10-09/APIReference/API_Validator.html) and [automated rollback](https://docs.aws.amazon.com/appconfig/latest/userguide/getting-started-with-appconfig-cloudwatch-alarms-permissions.html). With these features it should be more difficult for users to accidentally push broken configurations.

**Describe the solution you'd like**

Add support for the following:
- AppConfig validator
- AppConfig configuration rollback

**Describe alternatives you've considered**

Validation can also be performed within our [configuration library](https://substation.readme.io/docs/configuration-library) using assertion (see [Errors on this page](https://jsonnet.org/learning/tutorial.html)). There is no alternative for configuration rollback, though users should monitor their deployments via CloudWatch to identify data processing failures.

**Additional context**
N/A

**Comment by shellcromancer** [comment]
Inclusion of an AWS AppConfig Validation Lambda, and helper CI script are slated for the v0.9.0 release. Remaining work involves automated rollbacks.

**Comment by shellcromancer** [comment]
After some discussion we're happy with the safety benefits teams can get with the new validation implementation in [Substation v0.9.0](https://github.com/brexhq/substation/releases/tag/v0.9.0) across testing before deployments, and gating deployments on these safety issues. Due to this we're going to de-prioritize AppConfig Automated Rollbacks and will address those later under a separate issue.
